#!/bin/sh
#
# This is a minmal rcS file for target startup
#

VERBOSE=y

# Start script or program.
startup() {
  # Handle verbosity
  [ "$VERBOSE" = y ] && echo "INIT: Running $@..."

  case "$1" in
	*.sh)
		# Source shell script for speed.
		(
			trap - INT QUIT TSTP
			scriptname=$1
			shift
			. $scriptname
		)
		;;
	*)
		"$@"
		;;
  esac
}

# Make sure that /proc and /sys is mounted.
[ -d /proc ] || mkdir /proc
[ -d /sys ] || mkdir /sys
[ -d /tmp ] || mkdir /tmp
[ -d /var/run ] || mkdir -p /var/run
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /tmp
mount -t tmpfs tmpfs /var/run

# Fire startup scripts
. /etc/init.d/rc S

exit 0
