inherit cross
RECIPE_TYPE = "sdk-cross"

# Set target=sdk to get architecture triplet build/build/sdk
TARGET_ARCH		= "${SDK_ARCH}"
TARGET_CPU		= "${SDK_CPU}"
TARGET_OS		= "${SDK_OS}"
TARGET_CPU_CROSS	= "${SDK_CPU_CROSS}"
TARGET_CROSS		= "${SDK_CROSS}"
TARGET_CC_ARCH		= "${SDK_CC_ARCH}"
TARGET_EXEEXT		= "${SDK_EXEEXT}"
TARGET_PREFIX		= "${SDK_PREFIX}"
TARGET_CPPFLAGS		= "${SDK_CPPFLAGS}"
TARGET_CFLAGS		= "${SDK_CFLAGS}"
TARGET_CXXFLAGS		= "${SDK_CXXFLAGS}"
TARGET_LDFLAGS		= "${SDK_LDFLAGS}"
