BBCLASS = 'sdk-cross'
inherit cross

#
SYSROOT_PACKAGE_OUTPUT_ARCH	= "${PACKAGE_DIR_SDK_ARCH}"
SYSROOT_PACKAGE_OUTPUT_MACHINE	= "${PACKAGE_DIR_SDK_MACHINE}"

# Set target=sdk to get architecture triplet build/build/sdk
TARGET_ARCH		= "${SDK_ARCH}"
TARGET_CPU		= "${SDK_CPU}"
TARGET_OS		= "${SDK_OS}"
TARGET_CPU_CROSS	= "${SDK_CPU_CROSS}"
TARGET_CROSS		= "${SDK_CROSS}"
TARGET_CC_ARCH		= "${SDK_CC_ARCH}"
TARGET_EXEEXT		= "${SDK_EXEEXT}"
TARGET_PREFIX		= "${SDK_PREFIX}"
